export default {
  'zh-CN': { mode: { code: '代码' }, status: { codeLanguage: '代码语言', codeLanguageAuto: '自动检测', codeLanguagePlain: '纯代码（不指定语言）', codeLanguageDetected: '检测为 {language}，置信度 {confidence}%', codeLanguageUncertain: '暂时无法可靠判断语言，按纯代码显示', codeLanguageCandidates: '可能是：{candidates}' }, editor: { loadingCode: '正在加载代码编辑器', codeImageAria: '代码图片编辑器', untitledFile: '未命名-1' } },
  'zh-HK': { mode: { code: '程式碼' }, status: { codeLanguage: '程式語言', codeLanguageAuto: '自動偵測', codeLanguagePlain: '純程式碼（不指定語言）', codeLanguageDetected: '偵測為 {language}，可信度 {confidence}%', codeLanguageUncertain: '暫時無法可靠判斷語言，將以純程式碼顯示', codeLanguageCandidates: '可能是：{candidates}' }, editor: { loadingCode: '正在載入程式碼編輯器', codeImageAria: '程式碼圖片編輯器', untitledFile: '未命名-1' } },
  'zh-TW': { mode: { code: '程式碼' }, status: { codeLanguage: '程式語言', codeLanguageAuto: '自動偵測', codeLanguagePlain: '純程式碼（不指定語言）', codeLanguageDetected: '偵測為 {language}，可信度 {confidence}%', codeLanguageUncertain: '暫時無法可靠判斷語言，將以純程式碼顯示', codeLanguageCandidates: '可能是：{candidates}' }, editor: { loadingCode: '正在載入程式碼編輯器', codeImageAria: '程式碼圖片編輯器', untitledFile: '未命名-1' } },
  en: { mode: { code: 'Code' }, status: { codeLanguage: 'Code language', codeLanguageAuto: 'Automatic detection', codeLanguagePlain: 'Plain code (no language)', codeLanguageDetected: 'Detected as {language}, {confidence}% confidence', codeLanguageUncertain: 'The language cannot be identified reliably yet; showing plain code', codeLanguageCandidates: 'Possibly: {candidates}' }, editor: { loadingCode: 'Loading the code editor', codeImageAria: 'Code image editor', untitledFile: 'Untitled-1' } },
  ja: { mode: { code: 'コード' }, status: { codeLanguage: 'プログラミング言語', codeLanguageAuto: '自動判定', codeLanguagePlain: 'プレーンコード（言語指定なし）', codeLanguageDetected: '{language} と判定（信頼度 {confidence}%）', codeLanguageUncertain: '言語を確実に判定できないため、プレーンコードとして表示します', codeLanguageCandidates: '候補：{candidates}' }, editor: { loadingCode: 'コードエディターを読み込み中', codeImageAria: 'コード画像エディター', untitledFile: '無題-1' } },
  vi: { mode: { code: 'Mã nguồn' }, status: { codeLanguage: 'Ngôn ngữ lập trình', codeLanguageAuto: 'Tự động nhận dạng', codeLanguagePlain: 'Mã thuần (không chọn ngôn ngữ)', codeLanguageDetected: 'Đã nhận dạng là {language}, độ tin cậy {confidence}%', codeLanguageUncertain: 'Chưa thể xác định ngôn ngữ một cách đáng tin cậy; hiển thị dưới dạng mã thuần', codeLanguageCandidates: 'Có thể là: {candidates}' }, editor: { loadingCode: 'Đang tải trình soạn thảo mã', codeImageAria: 'Trình sửa mã cho ảnh', untitledFile: 'Chưa đặt tên-1' } },
  ko: { mode: { code: '코드' }, status: { codeLanguage: '프로그래밍 언어', codeLanguageAuto: '자동 감지', codeLanguagePlain: '일반 코드(언어 지정 안 함)', codeLanguageDetected: '{language}(으)로 감지됨, 신뢰도 {confidence}%', codeLanguageUncertain: '언어를 확실하게 판단할 수 없어 일반 코드로 표시합니다', codeLanguageCandidates: '가능한 언어: {candidates}' }, editor: { loadingCode: '코드 편집기 불러오는 중', codeImageAria: '코드 이미지 편집기', untitledFile: '제목 없음-1' } },
  es: { mode: { code: 'Código' }, status: { codeLanguage: 'Lenguaje de programación', codeLanguageAuto: 'Detección automática', codeLanguagePlain: 'Código sin lenguaje asignado', codeLanguageDetected: 'Detectado como {language}, confianza del {confidence}%', codeLanguageUncertain: 'Todavía no se puede identificar el lenguaje con fiabilidad; se muestra como código sin lenguaje', codeLanguageCandidates: 'Podría ser: {candidates}' }, editor: { loadingCode: 'Cargando el editor de código', codeImageAria: 'Editor de código para la imagen', untitledFile: 'Sin título-1' } },
  fr: { mode: { code: 'Programmation' }, status: { codeLanguage: 'Langage de programmation', codeLanguageAuto: 'Détection automatique', codeLanguagePlain: 'Code brut (sans langage)', codeLanguageDetected: 'Détecté comme {language}, confiance de {confidence} %', codeLanguageUncertain: 'Le langage ne peut pas encore être identifié avec fiabilité ; affichage en code brut', codeLanguageCandidates: 'Langages possibles : {candidates}' }, editor: { loadingCode: 'Chargement de l’éditeur de code', codeImageAria: 'Éditeur de code de l’image', untitledFile: 'Sans titre-1' } },
  'pt-BR': { mode: { code: 'Código' }, status: { codeLanguage: 'Linguagem de programação', codeLanguageAuto: 'Detecção automática', codeLanguagePlain: 'Código simples (sem linguagem)', codeLanguageDetected: 'Detectado como {language}, confiança de {confidence}%', codeLanguageUncertain: 'Ainda não foi possível identificar a linguagem com segurança; exibindo como código simples', codeLanguageCandidates: 'Pode ser: {candidates}' }, editor: { loadingCode: 'Carregando o editor de código', codeImageAria: 'Editor de código da imagem', untitledFile: 'Sem título-1' } },
  'pt-PT': { mode: { code: 'Código' }, status: { codeLanguage: 'Linguagem de programação', codeLanguageAuto: 'Deteção automática', codeLanguagePlain: 'Código simples (sem linguagem)', codeLanguageDetected: 'Detetado como {language}, confiança de {confidence}%', codeLanguageUncertain: 'Ainda não é possível identificar a linguagem com segurança; a mostrar como código simples', codeLanguageCandidates: 'Pode ser: {candidates}' }, editor: { loadingCode: 'A carregar o editor de código', codeImageAria: 'Editor de código da imagem', untitledFile: 'Sem título-1' } },
  ru: { mode: { code: 'Код' }, status: { codeLanguage: 'Язык программирования', codeLanguageAuto: 'Определять автоматически', codeLanguagePlain: 'Код без указания языка', codeLanguageDetected: 'Определён язык {language}, уверенность {confidence} %', codeLanguageUncertain: 'Надёжно определить язык пока не удалось; код показан без подсветки языка', codeLanguageCandidates: 'Возможные языки: {candidates}' }, editor: { loadingCode: 'Загрузка редактора кода', codeImageAria: 'Редактор кода для изображения', untitledFile: 'Без названия-1' } },
  de: { mode: { code: 'Quellcode' }, status: { codeLanguage: 'Programmiersprache', codeLanguageAuto: 'Automatisch erkennen', codeLanguagePlain: 'Reiner Code (ohne Sprache)', codeLanguageDetected: 'Als {language} erkannt, Konfidenz {confidence} %', codeLanguageUncertain: 'Die Sprache lässt sich noch nicht zuverlässig erkennen; Anzeige als reiner Code', codeLanguageCandidates: 'Möglicherweise: {candidates}' }, editor: { loadingCode: 'Code-Editor wird geladen', codeImageAria: 'Code-Editor für das Bild', untitledFile: 'Unbenannt-1' } },
  it: { mode: { code: 'Codice' }, status: { codeLanguage: 'Linguaggio di programmazione', codeLanguageAuto: 'Rilevamento automatico', codeLanguagePlain: 'Codice semplice (senza linguaggio)', codeLanguageDetected: 'Rilevato come {language}, attendibilità {confidence}%', codeLanguageUncertain: 'Non è ancora possibile identificare il linguaggio in modo affidabile; visualizzazione come codice semplice', codeLanguageCandidates: 'Potrebbe essere: {candidates}' }, editor: { loadingCode: 'Caricamento dell’editor di codice', codeImageAria: 'Editor del codice per l’immagine', untitledFile: 'Senza titolo-1' } }
}
