export default {
  app: { name: '闪念文本' },
  autoSave: { title: 'Save entries automatically', workflowDescription: 'When enabled, changes are saved to the current entry automatically', helpDescription: 'The automatic-save button at the top has on and off states. When on, it writes to the current entry 150 ms after typing stops. When off, leaving the plugin, switching entries, or saving a file does not write changes to history; the current content is kept only as a recovery draft.', guideMessage: '• Use the automatic-save button to pause or resume writes to history. When it is off, uncommitted content is kept only as a recovery draft and does not create or overwrite a history entry.' },
  sidebar: { autoSaveEntries: 'Save entries automatically' },
  fileDialog: { textFiles: 'Text files', allFiles: 'All files', defaultName: '闪念文本', saveButton: 'Save', detachRequired: 'Press Ctrl+D to detach the “FlashNote Text” plugin into a separate window.' },
  common: { cancel: 'Cancel', close: 'Close', clear: 'Clear', go: 'Go', applyRemove: 'Apply and remove' },
  settings: {
    title: 'Settings', theme: 'Theme', themeAuto: 'Automatic', themeLight: 'Daylight', themeDark: 'Night mode', language: 'Display language', languageAuto: 'Automatic (system language)',
    startup: 'When opening the plugin', startupNew: 'New entry', startupRestore: 'Last viewed entry', shortcuts: 'Keyboard shortcuts', toggleSidebar: 'Expand or collapse the feature sidebar', resetShortcut: 'Reset shortcut',
    shortcutInvalid: 'Use Ctrl, Alt, or Meta with another key, or use F1-F12', shortcutReserved: 'This shortcut is already used by the editor', retention: 'History retention', byCount: 'By count', byTime: 'By time',
    commonDuration: 'Common duration', customDuration: 'Custom: {duration}', exactDays: 'Exact number of days', ageRange: 'Range: {min} days to {max}', ageInvalid: 'Enter a whole number of days from {min} to {max}',
    maxEntries: 'Maximum entries', countRange: 'Range: {min}-{max}', countInvalid: 'Enter a whole number from {min} to {max}', wordWrap: 'Wrap text in the editor', rememberSidebarState: 'Remember whether the feature sidebar is expanded or collapsed'
  },
  editor: { loadingMarkdown: 'Loading the Markdown editor', historyPreview: 'History entry preview', readOnlyPreview: 'Read-only preview', noContent: 'No content', aria: '闪念文本 editor', placeholder: 'Type text here...' },
  search: { matches: { one: '{count} match', other: '{count} matches' }, noMatches: 'No matches', findReplace: 'Find and replace', findDocument: 'Find in document', find: 'Find', previous: 'Previous match', next: 'Next match', close: 'Close', closeBar: 'Close find bar', replaceWith: 'Replace with', replace: 'Replace', all: 'All' },
  history: {
    newEntry: 'New entry', newEntryShortcut: 'New entry (Ctrl+N)', copyText: 'Copy text', search: 'Search history', searchScope: 'Search history titles and contents', closeSearch: 'Close history search', searching: 'Searching...',
    results: 'Results {visible}/{total}', title: 'History', clearAll: 'Clear all history', clear: 'Clear history', noHistory: 'No history yet', searchingFull: 'Searching titles and contents...', noMatching: 'No matching history entries',
    rename: 'Rename history entry', deleteNamed: 'Delete history entry: {title}', settings: 'Settings', guide: 'User guide', openFile: 'Open file', openFileShortcut: 'Open file (Ctrl+O)', saveFile: 'Save file', saveFileShortcut: 'Save file (Ctrl+S)'
  },
  status: {
    characters: { one: '{count} character', other: '{count} characters' }, unicodeText: 'Unicode text', editorStatus: 'Editor status', collapseSidebarAria: 'Collapse feature sidebar ({shortcut})', expandSidebarAria: 'Expand feature sidebar ({shortcut})', collapseSidebar: 'Collapse sidebar', expandSidebar: 'Expand sidebar',
    totalCharacters: 'Total characters', effectiveCharacters: 'Characters excluding spaces', cjkCharacters: 'Basic CJK characters', wordsPhrases: 'Words and phrases', latinLetters: 'Latin letters', arabicDigits: 'Arabic numerals', punctuation: 'Punctuation marks', nonEmptyLines: 'Non-empty lines',
    editorMode: 'Editor mode', zoom: 'Zoom: {zoom}%', zoomOut: 'Zoom out', resetZoom: 'Reset zoom', zoomIn: 'Zoom in', lineEndingSaving: 'Line ending used when saving', classicMac: 'Classic Mac (CR)', mixedPreserve: 'Mixed (preserve)',
    historyUnicode: 'History is stored as Unicode text', fileEncoding: 'File encoding: {encoding}', savingEncoding: 'Encoding used when saving: {encoding}', lowConfidence: 'Encoding detection confidence is low. Try another encoding if the text looks wrong.', candidates: 'Candidates:', reloadEncoding: 'Reload with this encoding'
  },
  dialogs: { clearTitle: 'Clear history', clearBody: 'Delete all {count} history entries?', retentionTitle: 'Apply history retention', retentionBody: { one: 'The new retention rule will permanently remove {count} entry that exceeds the limit. Continue?', other: 'The new retention rule will permanently remove {count} entries that exceed the limit. Continue?' }, goToLine: 'Go to line', lineNumber: 'Line number (1-{count})' },
  help: {
    startGuide: 'Start tutorial', workflow: 'Core workflow', history: 'History entry', historyDesc: 'Create or focus a temporary entry', editor: 'Focused editing', editorDesc: 'The editor shows only the current entry', autosave: 'Automatic storage', autosaveDesc: 'Changes are written back to the same entry', features: 'Everyday features', shortcuts: 'Keyboard shortcuts', close: 'Close user guide',
    featureEntryTitle: 'Entry-based storage', featureEntryDesc: 'Ctrl+N creates an entry immediately. Editing updates that entry; deleting it focuses the next one.', featureSearchTitle: 'Two search scopes', featureSearchDesc: 'Sidebar search scans every title and body. Ctrl+F and Ctrl+H work only in the focused entry.',
    featurePreviewTitle: 'Hover preview and ordering', featurePreviewDesc: 'Hover another entry for 500 ms to preview its full contents in the editor, or drag the card itself to reorder it.', featureMarkdownTitle: 'Plain text and Markdown', featureMarkdownDesc: 'Plain text and Markdown share one editor. Ctrl+/ switches the focused entry between the two modes.',
    featureEncodingTitle: 'Text files in multiple encodings', featureEncodingDesc: 'Common encodings are detected automatically when opening a file. You can reload manually and choose the encoding used for saving from the status bar.', featureEmptyTitle: 'Automatic cleanup of empty entries', featureEmptyDesc: 'Entries with neither a title nor content are not retained, so they never consume history capacity.',
    shortcutNew: 'New entry', shortcutFind: 'Find in entry', shortcutReplace: 'Find and replace in entry', shortcutMode: 'Switch plain text / Markdown', shortcutBold: 'Bold', shortcutItalic: 'Italic', shortcutOpen: 'Open file', shortcutSave: 'Save file', shortcutUndo: 'Undo', shortcutRedo: 'Redo', shortcutGoLine: 'Go to line', shortcutZoom: 'Editor zoom', shortcutSidebar: 'Expand / collapse sidebar', shortcutRename: 'Rename hovered entry', shortcutDelete: 'Delete hovered entry', shortcutEscape: 'Close the active panel or dialog'
  },
  guide: {
    skip: 'Skip', back: 'Back', next: 'Next', finish: 'Finish',
    historyTitle: 'History and focus', historyMessage: 'The editor always belongs to the focused entry.\n\n• Click an entry to focus it.\n• Hover another entry for 500 ms to preview it temporarily.\n• Drag the whole card to reorder it; while hovering, press {key:F2} or {key:Delete}.',
    actionsTitle: 'Common entry actions', actionsMessage: 'The top toolbar contains the actions used most often in 闪念文本.\n\n• {bold:New} creates and focuses an entry ({key:Ctrl+N}).\n• {bold:Copy} copies the entry currently shown.\n• {bold:Search} matches titles and contents across the entire history.',
    editorTitle: 'Plain text and Markdown', editorMessage: 'Edit the focused entry here. Changes are automatically written back to the same history entry.\n\n• {key:Ctrl+/} switches between plain text and Markdown.\n• {key:Ctrl+F} finds text; {key:Ctrl+H} finds and replaces it.\n• {key:Ctrl+Z} and {key:Ctrl+Shift+Z} undo and redo actions.',
    statusTitle: 'Document status and controls', statusMessage: 'Hover a status area to open its controls.\n\n• View detailed document statistics.\n• Change the editing mode and zoom.\n• Choose the line ending and file encoding.\n• Use the leftmost area to expand or collapse the feature sidebar.',
    toolsTitle: 'Files, settings, and help', toolsMessage: 'Global tools are at the bottom of the sidebar.\n\n• Configure the theme, language, history retention, and startup behavior.\n• Restart this tutorial from the user guide.\n• Open encoded text files or save the focused entry to a location you choose each time.'
  },
  notice: {
    draftSaveFailed: 'Could not save the recovery draft', apiUnavailable: 'The uTools API is unavailable', nothingUndo: 'There is nothing to undo', undone: 'Undone', undoFailed: 'Undo failed', nothingRedo: 'There is nothing to redo', redone: 'Redone', redoFailed: 'Redo failed', saveFailed: 'Save failed', textTooLong: 'Text cannot exceed {max} characters', fileRequiresUtools: 'File features are available only inside uTools', modeSaveFailed: 'Could not save the editing mode', themeSaveFailed: 'Could not save the theme setting', languageSaveFailed: 'Could not save the language setting', startupSaveFailed: 'Could not save the startup behavior', shortcutSet: 'Sidebar shortcut set to {shortcut}', shortcutSaveFailed: 'Could not save the sidebar shortcut', runInUtools: 'Run this plugin inside uTools', draftRecovered: 'Recovered an unsaved draft', localLoadFailed: 'Could not load local data', startupApplyFailed: 'Could not apply the startup behavior', conflictCopyTitle: 'Local conflict copy', conflictPreserved: 'A sync conflict was detected. The local copy has been preserved.', syncFailed: 'History synchronization failed', copied: 'Text copied', copyFailed: 'Copy failed', openedLowConfidence: 'Opened {name}. Encoding detection confidence is low; please verify the text.', opened: 'Opened {name}', saved: 'Saved {name}', nothingSave: 'There is no content to save', noAssociatedFile: 'The current content is not associated with a file', reloadedEncoding: 'Reloaded using {encoding}', boldMarkdownOnly: 'Bold is available only in Markdown mode', italicMarkdownOnly: 'Italic is available only in Markdown mode', lineRange: 'Enter a line number from 1 to {count}', zoomSaveFailed: 'Could not save the zoom setting', newEntry: 'New blank entry created', newEntryFailed: 'Could not create the entry', copyWindowKept: 'Copy failed. The current window has been kept open.', deletedOne: 'Deleted 1 history entry', deleteFailed: 'Delete failed', titleUpdated: 'History title updated', renameFailed: 'Rename failed', reorderFailed: 'Could not save the history order', historyCleared: 'History cleared', clearFailed: 'Clearing failed. The remaining history has been reloaded.', retentionTimeSet: 'History retention set to {duration}', retentionCountSet: 'History limit set to {count}', settingsSaveFailed: 'Could not save the settings', wordWrapSaveFailed: 'Could not save the word-wrap setting', tutorialCompleted: 'Tutorial completed', noMatches: 'No matches found', enterFind: 'Enter text to find', replacedOne: 'Replaced 1 occurrence', replacedMany: { one: 'Replaced {count} occurrence', other: 'Replaced {count} occurrences' }
  },
  fileError: { binary: 'This appears to be a binary file and cannot be opened as text', encodingLoss: 'The selected encoding cannot represent some characters. Use UTF-8 or another compatible encoding.', tooLarge: 'The file is too large. The limit is {max} characters.', notFile: 'The selected path is not a file', textTooLong: 'Text cannot exceed {max} characters', generic: 'File operation failed' },
  error: { unknown: 'Unknown error', operation: 'An operation failed', background: 'A background operation failed', details: 'Technical details', close: 'Close', copyDetails: 'Copy details', renderError: 'Interface rendering error', reload: 'Reload', renderTitle: 'The interface could not be displayed', renderBody: 'Reload the plugin. Your current content and history are normally still stored locally.' },
  mode: { text: 'Plain text', markdown: 'Markdown' },
  lineEnding: { mixed: 'Mixed (preserve)', classicMac: 'Classic Mac (CR)' },
  time: { justNow: 'just now' },
  age: { days: { one: '{count} day', other: '{count} days' }, months: { one: '{count} month', other: '{count} months' }, years: { one: '{count} year', other: '{count} years' } }
}
