export default {
  'zh-CN': { interfaceFont: '界面字体', defaultInterfaceFont: '系统字体（默认）', contentFont: '内容字体', defaultContentFont: '霞鹜文楷（默认）', fontLoading: '正在读取本机字体…', fontUnavailable: '无法读取本机字体' },
  'zh-HK': { interfaceFont: '介面字型', defaultInterfaceFont: '系統字型（預設）', contentFont: '內容字型', defaultContentFont: '霞鶩文楷（預設）', fontLoading: '正在讀取本機字型…', fontUnavailable: '無法讀取本機字型' },
  'zh-TW': { interfaceFont: '介面字型', defaultInterfaceFont: '系統字型（預設）', contentFont: '內容字型', defaultContentFont: '霞鶩文楷（預設）', fontLoading: '正在讀取本機字型…', fontUnavailable: '無法讀取本機字型' },
  en: { interfaceFont: 'Interface font', defaultInterfaceFont: 'System font (default)', contentFont: 'Content font', defaultContentFont: 'LXGW WenKai (default)', fontLoading: 'Loading local fonts…', fontUnavailable: 'Local fonts could not be read' },
  ja: { interfaceFont: 'インターフェイスのフォント', defaultInterfaceFont: 'システムフォント（デフォルト）', contentFont: 'コンテンツのフォント', defaultContentFont: 'LXGW WenKai（デフォルト）', fontLoading: 'ローカルフォントを読み込んでいます…', fontUnavailable: 'ローカルフォントを読み込めません' },
  vi: { interfaceFont: 'Phông chữ giao diện', defaultInterfaceFont: 'Phông chữ hệ thống (mặc định)', contentFont: 'Phông chữ nội dung', defaultContentFont: 'LXGW WenKai (mặc định)', fontLoading: 'Đang tải phông chữ trên máy…', fontUnavailable: 'Không thể đọc phông chữ trên máy' },
  ko: { interfaceFont: '인터페이스 글꼴', defaultInterfaceFont: '시스템 글꼴(기본값)', contentFont: '콘텐츠 글꼴', defaultContentFont: 'LXGW WenKai(기본값)', fontLoading: '로컬 글꼴을 불러오는 중…', fontUnavailable: '로컬 글꼴을 불러올 수 없습니다' },
  es: { interfaceFont: 'Fuente de la interfaz', defaultInterfaceFont: 'Fuente del sistema (predeterminada)', contentFont: 'Fuente del contenido', defaultContentFont: 'LXGW WenKai (predeterminada)', fontLoading: 'Cargando fuentes locales…', fontUnavailable: 'No se pueden leer las fuentes locales' },
  fr: { interfaceFont: 'Police de l’interface', defaultInterfaceFont: 'Police système (par défaut)', contentFont: 'Police du contenu', defaultContentFont: 'LXGW WenKai (par défaut)', fontLoading: 'Chargement des polices locales…', fontUnavailable: 'Impossible de lire les polices locales' },
  'pt-BR': { interfaceFont: 'Fonte da interface', defaultInterfaceFont: 'Fonte do sistema (padrão)', contentFont: 'Fonte do conteúdo', defaultContentFont: 'LXGW WenKai (padrão)', fontLoading: 'Carregando fontes locais…', fontUnavailable: 'Não foi possível ler as fontes locais' },
  'pt-PT': { interfaceFont: 'Tipo de letra da interface', defaultInterfaceFont: 'Tipo de letra do sistema (predefinido)', contentFont: 'Tipo de letra do conteúdo', defaultContentFont: 'LXGW WenKai (predefinido)', fontLoading: 'A carregar tipos de letra locais…', fontUnavailable: 'Não foi possível ler os tipos de letra locais' },
  ru: { interfaceFont: 'Шрифт интерфейса', defaultInterfaceFont: 'Системный шрифт (по умолчанию)', contentFont: 'Шрифт содержимого', defaultContentFont: 'LXGW WenKai (по умолчанию)', fontLoading: 'Загрузка локальных шрифтов…', fontUnavailable: 'Не удалось прочитать локальные шрифты' },
  de: { interfaceFont: 'Oberflächenschrift', defaultInterfaceFont: 'Systemschrift (Standard)', contentFont: 'Inhaltsschrift', defaultContentFont: 'LXGW WenKai (Standard)', fontLoading: 'Lokale Schriften werden geladen…', fontUnavailable: 'Lokale Schriften konnten nicht gelesen werden' },
  it: { interfaceFont: 'Font dell’interfaccia', defaultInterfaceFont: 'Font di sistema (predefinito)', contentFont: 'Font dei contenuti', defaultContentFont: 'LXGW WenKai (predefinito)', fontLoading: 'Caricamento dei font locali…', fontUnavailable: 'Impossibile leggere i font locali' }
}
