export default {
  'zh-CN': { imageSaveDirectory: '图片保存位置', chooseImageSaveDirectory: '选择图片保存文件夹', defaultImageSaveDirectory: '系统下载文件夹', imageSaveDirectoryHint: '生成的分享图片将直接保存到这里', resetImageSaveDirectory: '恢复到系统下载文件夹' },
  'zh-HK': { imageSaveDirectory: '圖片儲存位置', chooseImageSaveDirectory: '選擇圖片儲存資料夾', defaultImageSaveDirectory: '系統下載資料夾', imageSaveDirectoryHint: '產生的分享圖片將直接儲存到這裡', resetImageSaveDirectory: '還原為系統下載資料夾' },
  'zh-TW': { imageSaveDirectory: '圖片儲存位置', chooseImageSaveDirectory: '選擇圖片儲存資料夾', defaultImageSaveDirectory: '系統下載資料夾', imageSaveDirectoryHint: '產生的分享圖片將直接儲存到這裡', resetImageSaveDirectory: '還原為系統下載資料夾' },
  en: { imageSaveDirectory: 'Image save location', chooseImageSaveDirectory: 'Choose image folder', defaultImageSaveDirectory: 'System Downloads folder', imageSaveDirectoryHint: 'Generated share images are saved here directly', resetImageSaveDirectory: 'Reset to the system Downloads folder' },
  ja: { imageSaveDirectory: '画像の保存先', chooseImageSaveDirectory: '画像の保存フォルダーを選択', defaultImageSaveDirectory: 'システムのダウンロードフォルダー', imageSaveDirectoryHint: '生成した共有画像はここに直接保存されます', resetImageSaveDirectory: 'システムのダウンロードフォルダーに戻す' },
  vi: { imageSaveDirectory: 'Vị trí lưu ảnh', chooseImageSaveDirectory: 'Chọn thư mục lưu ảnh', defaultImageSaveDirectory: 'Thư mục Tải xuống của hệ thống', imageSaveDirectoryHint: 'Ảnh chia sẻ đã tạo được lưu trực tiếp tại đây', resetImageSaveDirectory: 'Đặt lại về thư mục Tải xuống của hệ thống' },
  ko: { imageSaveDirectory: '이미지 저장 위치', chooseImageSaveDirectory: '이미지 저장 폴더 선택', defaultImageSaveDirectory: '시스템 다운로드 폴더', imageSaveDirectoryHint: '생성된 공유 이미지를 여기에 바로 저장합니다', resetImageSaveDirectory: '시스템 다운로드 폴더로 재설정' },
  es: { imageSaveDirectory: 'Ubicación de imágenes', chooseImageSaveDirectory: 'Elegir carpeta de imágenes', defaultImageSaveDirectory: 'Carpeta Descargas del sistema', imageSaveDirectoryHint: 'Las imágenes para compartir generadas se guardan aquí directamente', resetImageSaveDirectory: 'Restablecer la carpeta Descargas del sistema' },
  fr: { imageSaveDirectory: 'Emplacement des images', chooseImageSaveDirectory: 'Choisir le dossier des images', defaultImageSaveDirectory: 'Dossier Téléchargements du système', imageSaveDirectoryHint: 'Les images de partage générées sont enregistrées ici directement', resetImageSaveDirectory: 'Rétablir le dossier Téléchargements du système' },
  'pt-BR': { imageSaveDirectory: 'Local das imagens', chooseImageSaveDirectory: 'Escolher pasta de imagens', defaultImageSaveDirectory: 'Pasta Downloads do sistema', imageSaveDirectoryHint: 'As imagens de compartilhamento geradas são salvas diretamente aqui', resetImageSaveDirectory: 'Redefinir para a pasta Downloads do sistema' },
  'pt-PT': { imageSaveDirectory: 'Local das imagens', chooseImageSaveDirectory: 'Escolher pasta de imagens', defaultImageSaveDirectory: 'Pasta Transferências do sistema', imageSaveDirectoryHint: 'As imagens de partilha geradas são guardadas diretamente aqui', resetImageSaveDirectory: 'Repor a pasta Transferências do sistema' },
  ru: { imageSaveDirectory: 'Папка для изображений', chooseImageSaveDirectory: 'Выбрать папку для изображений', defaultImageSaveDirectory: 'Системная папка «Загрузки»', imageSaveDirectoryHint: 'Созданные изображения для публикации сохраняются прямо сюда', resetImageSaveDirectory: 'Вернуть системную папку «Загрузки»' },
  de: { imageSaveDirectory: 'Speicherort für Bilder', chooseImageSaveDirectory: 'Bilderordner auswählen', defaultImageSaveDirectory: 'Downloadordner des Systems', imageSaveDirectoryHint: 'Erstellte Bilder zum Teilen werden direkt hier gespeichert', resetImageSaveDirectory: 'Auf den Downloadordner des Systems zurücksetzen' },
  it: { imageSaveDirectory: 'Posizione delle immagini', chooseImageSaveDirectory: 'Scegli cartella immagini', defaultImageSaveDirectory: 'Cartella Download di sistema', imageSaveDirectoryHint: 'Le immagini di condivisione generate vengono salvate direttamente qui', resetImageSaveDirectory: 'Ripristina la cartella Download di sistema' }
}
