import en from './en'
import mergeLocale from './mergeLocale'

export default mergeLocale(en, {
  autoSave: { title: '項目の自動保存', workflowDescription: 'オンにすると、変更が現在の項目へ自動保存されます', helpDescription: '上部の自動保存ボタンはオン／オフを切り替えられます。オンでは入力が止まってから150ミリ秒後に現在の項目へ保存します。オフでは、プラグインを閉じるとき、項目を切り替えるとき、ファイルを保存するときにも変更を履歴へ書き込まず、現在の内容は復元用下書きとしてのみ保持します。', guideMessage: '• 自動保存ボタンで履歴への書き込みを一時停止／再開できます。オフでは、未確定の内容は復元用下書きとしてのみ保持され、履歴項目の新規作成や上書きは行われません。' },
  sidebar: { autoSaveEntries: '項目を自動保存' },
  fileDialog: { textFiles: 'テキストファイル', allFiles: 'すべてのファイル', defaultName: '闪念文本', saveButton: '保存', detachRequired: '先に Ctrl+D を押して「闪念文本」を独立ウィンドウに切り離してください。' },
  common: { cancel: 'キャンセル', close: '閉じる', clear: '消去', go: '移動', applyRemove: '適用して削除' },
  settings: { title: '設定', theme: 'テーマ', themeAuto: '自動調整', themeLight: 'ライト', themeDark: 'ダーク', language: '表示言語', languageAuto: '自動（システム設定に従う）', startup: 'プラグインを開いたとき', startupNew: '新しい項目', startupRestore: '前回表示した項目', shortcuts: 'ショートカットキー', toggleSidebar: '機能サイドバーの展開／折りたたみ', resetShortcut: 'ショートカットをリセット', shortcutInvalid: 'Ctrl、Alt、Meta のいずれかとの組み合わせ、または F1～F12 キーを使用してください', shortcutReserved: 'このショートカットはエディターですでに使用されています', retention: '履歴の保存期間', byCount: '件数で指定', byTime: '期間で指定', commonDuration: 'よく使う期間', customDuration: 'カスタム：{duration}', exactDays: '正確な日数', ageRange: '範囲：{min} 日～{max}', ageInvalid: '{min}～{max} の整数の日数を入力してください', maxEntries: '最大件数', countRange: '範囲：{min}～{max}', countInvalid: '{min}～{max} の整数を入力してください', wordWrap: 'エディター内で折り返す', rememberSidebarState: '機能サイドバーの開閉状態を記憶する' },
  editor: { loadingMarkdown: 'Markdown エディターを読み込んでいます', historyPreview: '履歴項目のプレビュー', readOnlyPreview: '読み取り専用プレビュー', noContent: '内容はありません', aria: '「闪念文本」テキストエディター', placeholder: 'ここにテキストを入力...' },
  search: { matches: '{count} 件一致', noMatches: '一致する項目はありません', findReplace: '検索と置換', findDocument: '文書内を検索', find: '検索', previous: '前の一致箇所', next: '次の一致箇所', close: '閉じる', closeBar: '検索バーを閉じる', replaceWith: '置換後の文字列', replace: '置換', all: 'すべて' },
  history: { newEntry: '新しい項目', newEntryShortcut: '新しい項目 (Ctrl+N)', copyText: 'テキストをコピー', search: '履歴を検索', searchScope: '履歴のタイトルと内容を検索', closeSearch: '履歴検索を閉じる', searching: '検索中...', results: '検索結果 {visible}/{total}', title: '履歴', clearAll: '履歴をすべて消去', clear: '履歴を消去', noHistory: '履歴はまだありません', searchingFull: 'タイトルと内容を検索しています...', noMatching: '一致する履歴はありません', rename: '履歴項目の名前を変更', deleteNamed: '履歴項目を削除：{title}', settings: '設定', guide: '使い方', openFile: 'ファイルを開く', openFileShortcut: 'ファイルを開く (Ctrl+O)', saveFile: 'ファイルを保存', saveFileShortcut: 'ファイルを保存 (Ctrl+S)' },
  status: { characters: '{count} 文字', unicodeText: 'Unicode テキスト', editorStatus: 'エディターの状態', collapseSidebarAria: '機能サイドバーを折りたたむ ({shortcut})', expandSidebarAria: '機能サイドバーを展開 ({shortcut})', collapseSidebar: 'サイドバーを折りたたむ', expandSidebar: 'サイドバーを展開', totalCharacters: '総文字数', effectiveCharacters: '空白を除く文字数', cjkCharacters: 'CJK 基本漢字', wordsPhrases: '単語／語句', latinLetters: 'ラテン文字', arabicDigits: '算用数字', punctuation: '句読点・記号', nonEmptyLines: '空行を除く行数', editorMode: '編集モード', zoom: 'ズーム：{zoom}%', zoomOut: '縮小', resetZoom: 'ズームをリセット', zoomIn: '拡大', lineEndingSaving: '保存時の改行コード', classicMac: '旧 Mac (CR)', mixedPreserve: '混在（維持）', historyUnicode: '履歴は Unicode テキストとして保存されます', fileEncoding: 'ファイルの文字コード：{encoding}', savingEncoding: '保存時の文字コード：{encoding}', lowConfidence: '文字コードの判定精度が低めです。文字化けしている場合は別の文字コードで読み直してください。', candidates: '候補：', reloadEncoding: 'この文字コードで読み直す' },
  dialogs: { clearTitle: '履歴を消去', clearBody: '履歴 {count} 件をすべて削除しますか？', retentionTitle: '履歴の保存設定を適用', retentionBody: '新しい保存条件を超える履歴 {count} 件が完全に削除されます。続行しますか？', goToLine: '指定行へ移動', lineNumber: '行番号（1～{count}）' },
  help: { startGuide: 'チュートリアルを開始', workflow: '基本の流れ', history: '履歴項目', historyDesc: '一時的な内容を新規作成または選択', editor: '選択項目を編集', editorDesc: 'エディターには現在の項目だけを表示', autosave: '自動保存', autosaveDesc: '変更内容を同じ履歴項目へ自動反映', features: '主な機能', shortcuts: 'ショートカット一覧', close: '使い方を閉じる', featureEntryTitle: '項目単位で一時保存', featureEntryDesc: 'Ctrl+N ですぐに項目を作成できます。編集内容は現在の項目に反映され、削除すると次の項目が自動的に選択されます。', featureSearchTitle: '2 種類の検索範囲', featureSearchDesc: 'サイドバー検索ではすべてのタイトルと内容を検索します。Ctrl+F と Ctrl+H は現在の項目だけが対象です。', featurePreviewTitle: 'ホバープレビューと並べ替え', featurePreviewDesc: '別の項目に 500 ミリ秒ポインターを合わせると、エディターで全文をプレビューできます。カード自体をドラッグして並べ替えることもできます。', featureMarkdownTitle: 'プレーンテキストと Markdown', featureMarkdownDesc: 'プレーンテキストと Markdown は同じエディターを使用します。Ctrl+/ で現在の項目の編集モードを切り替えます。', featureEncodingTitle: 'さまざまな文字コードのテキストファイル', featureEncodingDesc: 'ファイルを開くと一般的な文字コードを自動判定します。必要に応じて手動で読み直し、ステータスバーから保存時の文字コードを選べます。', featureEmptyTitle: '空の項目を自動整理', featureEmptyDesc: 'タイトルも内容もない項目は保存されないため、履歴の上限を無駄に消費しません。', shortcutNew: '新しい項目', shortcutFind: '項目内を検索', shortcutReplace: '項目内で検索と置換', shortcutMode: 'プレーンテキスト／Markdown を切り替え', shortcutBold: '太字', shortcutItalic: '斜体', shortcutOpen: 'ファイルを開く', shortcutSave: 'ファイルを保存', shortcutUndo: '元に戻す', shortcutRedo: 'やり直す', shortcutGoLine: '指定行へ移動', shortcutZoom: 'エディターのズーム', shortcutSidebar: 'サイドバーを展開／折りたたみ', shortcutRename: 'ポインター下の項目名を変更', shortcutDelete: 'ポインター下の項目を削除', shortcutEscape: '開いているパネルまたはダイアログを閉じる' },
  guide: { skip: 'スキップ', back: '戻る', next: '次へ', finish: '完了', historyTitle: '履歴と選択中の項目', historyMessage: 'エディターには、選択中の項目だけが表示されます。\n\n• 項目をクリックして選択します。\n• 別の項目に 500 ミリ秒ポインターを合わせると、一時的にプレビューできます。\n• カード全体をドラッグして並べ替えます。ポインターを合わせた状態で {key:F2} または {key:Delete} も使えます。', actionsTitle: 'よく使う項目操作', actionsMessage: '上部には、一時テキストでよく使う操作だけをまとめています。\n\n• {bold:新規}は項目を作成して選択します（{key:Ctrl+N}）。\n• {bold:コピー}は現在表示中の項目をコピーします。\n• {bold:検索}は履歴全体のタイトルと内容を検索します。', editorTitle: 'プレーンテキストと Markdown', editorMessage: 'ここで選択中の項目を編集します。変更は同じ履歴項目へ自動的に反映されます。\n\n• {key:Ctrl+/} でプレーンテキストと Markdown を切り替えます。\n• {key:Ctrl+F} で検索、{key:Ctrl+H} で検索と置換を行います。\n• {key:Ctrl+Z} と {key:Ctrl+Shift+Z} で元に戻す／やり直す操作を行います。', statusTitle: '文書の状態と操作', statusMessage: '各ステータス領域にポインターを合わせると、対応する操作が開きます。\n\n• 詳しい文書統計を確認できます。\n• 編集モードとズームを変更できます。\n• 改行コードと文字コードを選べます。\n• 一番左の領域で機能サイドバーを展開または折りたたみます。', toolsTitle: 'ファイル、設定、ヘルプ', toolsMessage: '全体に関するツールはサイドバー下部にあります。\n\n• テーマ、言語、履歴の保存条件、起動時の動作を設定します。\n• 使い方からこのチュートリアルをもう一度開始できます。\n• さまざまな文字コードのファイルを開いたり、選択中の項目を毎回指定した場所へ保存したりできます。' },
  notice: { draftSaveFailed: '復元用の下書きを保存できませんでした', apiUnavailable: 'uTools API を利用できません', nothingUndo: '元に戻せる操作はありません', undone: '元に戻しました', undoFailed: '元に戻せませんでした', nothingRedo: 'やり直せる操作はありません', redone: 'やり直しました', redoFailed: 'やり直せませんでした', saveFailed: '保存できませんでした', textTooLong: 'テキストは {max} 文字以内にしてください', fileRequiresUtools: 'ファイル機能は uTools 内でのみ利用できます', modeSaveFailed: '編集モードを保存できませんでした', themeSaveFailed: 'テーマ設定を保存できませんでした', languageSaveFailed: '言語設定を保存できませんでした', startupSaveFailed: '起動時の動作を保存できませんでした', shortcutSet: 'サイドバーのショートカットを {shortcut} に設定しました', shortcutSaveFailed: 'サイドバーのショートカットを保存できませんでした', runInUtools: 'このプラグインは uTools 内で実行してください', draftRecovered: '未保存の下書きを復元しました', localLoadFailed: 'ローカルデータを読み込めませんでした', startupApplyFailed: '起動時の動作を適用できませんでした', conflictCopyTitle: 'ローカル競合コピー', conflictPreserved: '同期の競合を検出したため、ローカルコピーを保持しました。', syncFailed: '履歴を同期できませんでした', copied: 'テキストをコピーしました', copyFailed: 'コピーできませんでした', openedLowConfidence: '{name} を開きました。文字コードの判定精度が低いため、内容を確認してください。', opened: '{name} を開きました', saved: '{name} を保存しました', nothingSave: '保存する内容がありません', noAssociatedFile: '現在の内容はファイルに関連付けられていません', reloadedEncoding: '{encoding} で読み直しました', boldMarkdownOnly: '太字は Markdown モードでのみ使用できます', italicMarkdownOnly: '斜体は Markdown モードでのみ使用できます', lineRange: '1～{count} の行番号を入力してください', zoomSaveFailed: 'ズーム設定を保存できませんでした', newEntry: '空の項目を追加しました', newEntryFailed: '項目を作成できませんでした', copyWindowKept: 'コピーできなかったため、現在のウィンドウを開いたままにしました。', deletedOne: '履歴を 1 件削除しました', deleteFailed: '削除できませんでした', titleUpdated: '履歴のタイトルを更新しました', renameFailed: '名前を変更できませんでした', reorderFailed: '履歴の並び順を保存できませんでした', historyCleared: '履歴を消去しました', clearFailed: '履歴を消去できませんでした。残りの履歴を読み直しました。', retentionTimeSet: '履歴の保存期間を {duration} に設定しました', retentionCountSet: '履歴の上限を {count} 件に設定しました', settingsSaveFailed: '設定を保存できませんでした', wordWrapSaveFailed: '折り返し設定を保存できませんでした', tutorialCompleted: 'チュートリアルが完了しました', noMatches: '一致する箇所はありません', enterFind: '検索する文字列を入力してください', replacedOne: '1 か所置換しました', replacedMany: '{count} か所置換しました' },
  fileError: { binary: 'バイナリファイルの可能性があるため、テキストとして開けません', encodingLoss: '選択した文字コードでは一部の文字を表せません。UTF-8 または対応する別の文字コードを使用してください。', tooLarge: 'ファイルが大きすぎます。上限は {max} 文字です。', notFile: '選択したパスはファイルではありません', textTooLong: 'テキストは {max} 文字以内にしてください', generic: 'ファイル操作に失敗しました' },
  error: { unknown: '不明なエラー', operation: '操作中にエラーが発生しました', background: 'バックグラウンド処理でエラーが発生しました', details: '技術情報', close: '閉じる', copyDetails: '詳細をコピー', renderError: '画面描画エラー', reload: '再読み込み', renderTitle: '画面を表示できません', renderBody: 'プラグインを再読み込みしてください。一時テキストと履歴は通常、ローカルに保存されたままです。' },
  mode: { text: 'プレーンテキスト', markdown: 'Markdown' }, lineEnding: { mixed: '混在（維持）', classicMac: '旧 Mac (CR)' }, time: { justNow: 'たった今' }, age: { days: '{count}日', months: '{count}か月', years: '{count}年' }
})
