import en from './en'
import mergeLocale from './mergeLocale'

export default mergeLocale(en, {
  autoSave: { title: '항목 자동 저장', workflowDescription: '켜면 변경 내용이 현재 항목에 자동으로 저장됩니다', helpDescription: '상단의 자동 저장 버튼은 켜짐과 꺼짐 두 상태로 전환됩니다. 켜면 입력을 멈춘 지 150ms 뒤 현재 항목에 저장합니다. 끄면 플러그인 종료, 항목 전환, 파일 저장 시에도 변경 내용을 기록에 쓰지 않으며 현재 내용은 복구용 초안으로만 보관합니다.', guideMessage: '• 자동 저장 버튼으로 기록 저장을 일시 중지하거나 다시 시작할 수 있습니다. 끄면 확정되지 않은 내용은 복구용 초안으로만 보관되며 기록 항목을 새로 만들거나 덮어쓰지 않습니다.' },
  sidebar: { autoSaveEntries: '항목 자동 저장' },
  fileDialog: { textFiles: '텍스트 파일', allFiles: '모든 파일', defaultName: '闪念文本', saveButton: '저장', detachRequired: '먼저 Ctrl+D를 눌러 “闪念文本”을 독립 창으로 분리하세요.' },
  common: { cancel: '취소', close: '닫기', clear: '지우기', go: '이동', applyRemove: '적용 후 삭제' },
  settings: { title: '설정', theme: '테마', themeAuto: '자동', themeLight: '밝은 모드', themeDark: '어두운 모드', language: '표시 언어', languageAuto: '자동(시스템 언어 따름)', startup: '플러그인을 열 때', startupNew: '새 항목', startupRestore: '마지막으로 본 항목', shortcuts: '키보드 단축키', toggleSidebar: '기능 사이드바 펼치기/접기', resetShortcut: '단축키 초기화', shortcutInvalid: 'Ctrl, Alt 또는 Meta 조합 키나 F1-F12 키를 사용하세요', shortcutReserved: '이 단축키는 편집기에서 이미 사용 중입니다', retention: '기록 보관', byCount: '개수 기준', byTime: '기간 기준', commonDuration: '자주 쓰는 기간', customDuration: '사용자 지정: {duration}', exactDays: '정확한 일수', ageRange: '범위: {min}일~{max}', ageInvalid: '{min}에서 {max} 사이의 정수 일수를 입력하세요', maxEntries: '최대 항목 수', countRange: '범위: {min}~{max}', countInvalid: '{min}에서 {max} 사이의 정수를 입력하세요', wordWrap: '편집기에서 자동 줄 바꿈', rememberSidebarState: '기능 사이드바의 펼침/접힘 상태 기억' },
  editor: { loadingMarkdown: 'Markdown 편집기를 불러오는 중', historyPreview: '기록 항목 미리 보기', readOnlyPreview: '읽기 전용 미리 보기', noContent: '내용 없음', aria: '闪念文本 텍스트 편집기', placeholder: '여기에 텍스트를 입력하세요...' },
  search: { matches: '{count}개 일치', noMatches: '일치 항목 없음', findReplace: '찾기 및 바꾸기', findDocument: '문서에서 찾기', find: '찾기', previous: '이전 일치 항목', next: '다음 일치 항목', close: '닫기', closeBar: '찾기 표시줄 닫기', replaceWith: '바꿀 내용', replace: '바꾸기', all: '모두' },
  history: { newEntry: '새 항목', newEntryShortcut: '새 항목 (Ctrl+N)', copyText: '텍스트 복사', search: '기록 검색', searchScope: '기록 제목과 내용 검색', closeSearch: '기록 검색 닫기', searching: '검색 중...', results: '검색 결과 {visible}/{total}', title: '기록', clearAll: '모든 기록 지우기', clear: '기록 지우기', noHistory: '아직 기록이 없습니다', searchingFull: '제목과 내용을 검색하는 중...', noMatching: '일치하는 기록이 없습니다', rename: '기록 항목 이름 바꾸기', deleteNamed: '기록 항목 삭제: {title}', settings: '설정', guide: '사용 안내', openFile: '파일 열기', openFileShortcut: '파일 열기 (Ctrl+O)', saveFile: '파일 저장', saveFileShortcut: '파일 저장 (Ctrl+S)' },
  status: { characters: '{count}자', unicodeText: 'Unicode 텍스트', editorStatus: '편집기 상태', collapseSidebarAria: '기능 사이드바 접기 ({shortcut})', expandSidebarAria: '기능 사이드바 펼치기 ({shortcut})', collapseSidebar: '사이드바 접기', expandSidebar: '사이드바 펼치기', totalCharacters: '전체 문자 수', effectiveCharacters: '공백 제외 문자 수', cjkCharacters: 'CJK 기본 한자', wordsPhrases: '단어/구', latinLetters: '라틴 문자', arabicDigits: '아라비아 숫자', punctuation: '문장 부호', nonEmptyLines: '빈 줄 제외 줄 수', editorMode: '편집 모드', zoom: '확대/축소: {zoom}%', zoomOut: '축소', resetZoom: '확대/축소 초기화', zoomIn: '확대', lineEndingSaving: '저장할 때 사용할 줄 바꿈 형식', classicMac: '구형 Mac (CR)', mixedPreserve: '혼합(유지)', historyUnicode: '기록은 Unicode 텍스트로 저장됩니다', fileEncoding: '파일 인코딩: {encoding}', savingEncoding: '저장 인코딩: {encoding}', lowConfidence: '인코딩 감지 신뢰도가 낮습니다. 글자가 깨져 보이면 다른 인코딩으로 다시 읽어 보세요.', candidates: '후보:', reloadEncoding: '이 인코딩으로 다시 읽기' },
  dialogs: { clearTitle: '기록 지우기', clearBody: '기록 {count}개를 모두 삭제할까요?', retentionTitle: '기록 보관 설정 적용', retentionBody: '새 보관 기준을 초과하는 기록 {count}개가 영구 삭제됩니다. 계속할까요?', goToLine: '줄로 이동', lineNumber: '줄 번호(1-{count})' },
  help: { startGuide: '초보자 안내 시작', workflow: '기본 작업 흐름', history: '기록 항목', historyDesc: '임시 항목을 만들거나 선택', editor: '선택 항목 편집', editorDesc: '편집기에는 현재 항목만 표시', autosave: '자동 임시 저장', autosaveDesc: '변경 내용이 같은 기록 항목에 자동 반영', features: '자주 쓰는 기능', shortcuts: '단축키 빠른 보기', close: '사용 안내 닫기', featureEntryTitle: '항목별 임시 저장', featureEntryDesc: 'Ctrl+N을 누르면 항목이 바로 만들어집니다. 편집 내용은 현재 항목에 반영되며, 삭제하면 다음 항목이 자동으로 선택됩니다.', featureSearchTitle: '두 가지 검색 범위', featureSearchDesc: '사이드바 검색은 모든 제목과 내용을 찾습니다. Ctrl+F와 Ctrl+H는 현재 항목 안에서만 작동합니다.', featurePreviewTitle: '가리키기 미리 보기와 정렬', featurePreviewDesc: '다른 항목을 500ms 동안 가리키면 편집기에서 전체 내용을 미리 볼 수 있습니다. 카드 전체를 끌어 순서를 바꿀 수도 있습니다.', featureMarkdownTitle: '보이는 그대로 Markdown 편집', featureMarkdownDesc: '일반 텍스트와 Markdown은 하나의 편집기를 공유합니다. Ctrl+/로 현재 항목의 편집 모드를 전환합니다.', featureEncodingTitle: '다양한 인코딩의 텍스트 파일', featureEncodingDesc: '파일을 열 때 일반적인 인코딩을 자동으로 감지합니다. 필요하면 수동으로 다시 읽고 상태 표시줄에서 저장 인코딩을 선택할 수 있습니다.', featureEmptyTitle: '빈 항목 자동 정리', featureEmptyDesc: '제목과 내용이 모두 없는 항목은 보관하지 않으므로 기록 용량을 차지하지 않습니다.', shortcutNew: '새 항목', shortcutFind: '항목에서 찾기', shortcutReplace: '항목에서 찾기 및 바꾸기', shortcutMode: '일반 텍스트/Markdown 전환', shortcutBold: '굵게', shortcutItalic: '기울임꼴', shortcutOpen: '파일 열기', shortcutSave: '파일 저장', shortcutUndo: '실행 취소', shortcutRedo: '다시 실행', shortcutGoLine: '줄로 이동', shortcutZoom: '편집기 확대/축소', shortcutSidebar: '사이드바 펼치기/접기', shortcutRename: '가리키는 항목 이름 바꾸기', shortcutDelete: '가리키는 항목 삭제', shortcutEscape: '현재 패널 또는 대화 상자 닫기' },
  guide: { skip: '건너뛰기', back: '이전', next: '다음', finish: '완료', historyTitle: '기록과 선택 항목', historyMessage: '편집기에는 선택된 항목만 표시됩니다.\n\n• 항목을 클릭해 선택합니다.\n• 다른 항목을 500ms 동안 가리키면 잠시 미리 볼 수 있습니다.\n• 카드 전체를 끌어 순서를 바꿉니다. 가리킨 상태에서는 {key:F2} 또는 {key:Delete}도 사용할 수 있습니다.', actionsTitle: '자주 쓰는 항목 작업', actionsMessage: '상단에는 임시 텍스트에 자주 쓰는 작업만 모아 두었습니다.\n\n• {bold:새 항목}은 항목을 만들고 선택합니다({key:Ctrl+N}).\n• {bold:복사}는 현재 표시된 항목을 복사합니다.\n• {bold:검색}은 전체 기록의 제목과 내용을 찾습니다.', editorTitle: '일반 텍스트와 Markdown', editorMessage: '여기에서 선택 항목을 편집합니다. 변경 내용은 같은 기록 항목에 자동으로 반영됩니다.\n\n• {key:Ctrl+/}로 일반 텍스트와 보이는 그대로의 Markdown을 전환합니다.\n• {key:Ctrl+F}로 찾고 {key:Ctrl+H}로 찾아 바꿉니다.\n• {key:Ctrl+Z}와 {key:Ctrl+Shift+Z}로 실행 취소와 다시 실행을 합니다.', statusTitle: '문서 상태와 제어', statusMessage: '각 상태 영역을 가리키면 관련 제어가 열립니다.\n\n• 자세한 문서 통계를 확인합니다.\n• 편집 모드와 확대/축소를 바꿉니다.\n• 줄 바꿈 형식과 파일 인코딩을 선택합니다.\n• 맨 왼쪽 영역에서 기능 사이드바를 펼치거나 접습니다.', toolsTitle: '파일, 설정 및 도움말', toolsMessage: '전체 도구는 사이드바 아래쪽에 있습니다.\n\n• 테마, 언어, 기록 보관 규칙과 시작 동작을 설정합니다.\n• 사용 안내에서 이 초보자 안내를 다시 시작할 수 있습니다.\n• 여러 인코딩의 텍스트 파일을 열거나 선택 항목을 매번 지정한 위치에 저장할 수 있습니다.' },
  notice: { draftSaveFailed: '복구용 초안을 저장하지 못했습니다', apiUnavailable: 'uTools API를 사용할 수 없습니다', nothingUndo: '실행 취소할 작업이 없습니다', undone: '실행 취소했습니다', undoFailed: '실행 취소하지 못했습니다', nothingRedo: '다시 실행할 작업이 없습니다', redone: '다시 실행했습니다', redoFailed: '다시 실행하지 못했습니다', saveFailed: '저장하지 못했습니다', textTooLong: '텍스트는 {max}자를 넘을 수 없습니다', fileRequiresUtools: '파일 기능은 uTools 안에서만 사용할 수 있습니다', modeSaveFailed: '편집 모드를 저장하지 못했습니다', themeSaveFailed: '테마 설정을 저장하지 못했습니다', languageSaveFailed: '언어 설정을 저장하지 못했습니다', startupSaveFailed: '시작 동작을 저장하지 못했습니다', shortcutSet: '사이드바 단축키를 {shortcut}(으)로 설정했습니다', shortcutSaveFailed: '사이드바 단축키를 저장하지 못했습니다', runInUtools: '이 플러그인은 uTools 안에서 실행하세요', draftRecovered: '저장되지 않은 초안을 복구했습니다', localLoadFailed: '로컬 데이터를 불러오지 못했습니다', startupApplyFailed: '시작 동작을 적용하지 못했습니다', conflictCopyTitle: '로컬 충돌 사본', conflictPreserved: '동기화 충돌을 감지하여 로컬 사본을 보관했습니다.', syncFailed: '기록을 동기화하지 못했습니다', copied: '텍스트를 복사했습니다', copyFailed: '복사하지 못했습니다', openedLowConfidence: '{name} 파일을 열었습니다. 인코딩 감지 신뢰도가 낮으니 내용을 확인하세요.', opened: '{name} 파일을 열었습니다', saved: '{name} 파일을 저장했습니다', nothingSave: '저장할 내용이 없습니다', noAssociatedFile: '현재 내용은 파일과 연결되어 있지 않습니다', reloadedEncoding: '{encoding}(으)로 다시 읽었습니다', boldMarkdownOnly: '굵게는 Markdown 모드에서만 사용할 수 있습니다', italicMarkdownOnly: '기울임꼴은 Markdown 모드에서만 사용할 수 있습니다', lineRange: '1에서 {count} 사이의 줄 번호를 입력하세요', zoomSaveFailed: '확대/축소 설정을 저장하지 못했습니다', newEntry: '빈 항목을 만들었습니다', newEntryFailed: '항목을 만들지 못했습니다', copyWindowKept: '복사하지 못해 현재 창을 그대로 열어 두었습니다.', deletedOne: '기록 1개를 삭제했습니다', deleteFailed: '삭제하지 못했습니다', titleUpdated: '기록 제목을 업데이트했습니다', renameFailed: '이름을 바꾸지 못했습니다', reorderFailed: '기록 순서를 저장하지 못했습니다', historyCleared: '기록을 지웠습니다', clearFailed: '기록을 모두 지우지 못해 남은 기록을 다시 불러왔습니다.', retentionTimeSet: '기록 보관 기간을 {duration}(으)로 설정했습니다', retentionCountSet: '기록 한도를 {count}개로 설정했습니다', settingsSaveFailed: '설정을 저장하지 못했습니다', wordWrapSaveFailed: '자동 줄 바꿈 설정을 저장하지 못했습니다', tutorialCompleted: '초보자 안내를 완료했습니다', noMatches: '일치 항목을 찾지 못했습니다', enterFind: '찾을 내용을 입력하세요', replacedOne: '1곳을 바꿨습니다', replacedMany: '{count}곳을 바꿨습니다' },
  fileError: { binary: '이 파일은 바이너리 파일일 수 있어 텍스트로 열 수 없습니다', encodingLoss: '선택한 인코딩으로 일부 문자를 표현할 수 없습니다. UTF-8 또는 다른 호환 인코딩을 사용하세요.', tooLarge: '파일이 너무 큽니다. 최대 {max}자까지 지원합니다.', notFile: '선택한 경로가 파일이 아닙니다', textTooLong: '텍스트는 {max}자를 넘을 수 없습니다', generic: '파일 작업에 실패했습니다' },
  error: { unknown: '알 수 없는 오류', operation: '작업 중 오류가 발생했습니다', background: '백그라운드 작업 중 오류가 발생했습니다', details: '기술 세부 정보', close: '닫기', copyDetails: '세부 정보 복사', renderError: '화면 렌더링 오류', reload: '다시 불러오기', renderTitle: '화면을 표시할 수 없습니다', renderBody: '플러그인을 다시 불러오세요. 임시 텍스트와 기록은 일반적으로 로컬에 그대로 저장되어 있습니다.' },
  mode: { text: '일반 텍스트', markdown: 'Markdown' }, lineEnding: { mixed: '혼합(유지)', classicMac: '구형 Mac (CR)' }, time: { justNow: '방금' }, age: { days: '{count}일', months: '{count}개월', years: '{count}년' }
})
