import zhCN from './zh-CN'
import mergeLocale from './mergeLocale'

export default mergeLocale(zhCN, {
  app: { name: '閃念文字' },
  autoSave: { title: '自動儲存項目', workflowDescription: '開啟後，修改會自動寫回目前項目', helpDescription: '頂部的自動儲存按鈕有開啟及關閉兩種狀態。開啟後，停止輸入 150 毫秒便會寫回目前項目；關閉後，離開外掛程式、切換項目或儲存檔案都不會將修改寫入歷史記錄，目前內容只會儲存為復原草稿。', guideMessage: '• 自動儲存按鈕可暫停或恢復寫入歷史記錄。關閉後，未提交內容只會保留為復原草稿，不會新增或覆寫歷史項目。' },
  sidebar: { autoSaveEntries: '自動儲存項目' },
  fileDialog: { textFiles: '文字檔案', allFiles: '所有檔案', defaultName: '閃念文字', saveButton: '儲存', detachRequired: '請先按 Ctrl+D 將「閃念文字」分離為獨立視窗。' },
  common: { cancel: '取消', close: '關閉', clear: '清除', go: '前往', applyRemove: '套用並刪除' },
  settings: {
    title: '設定', theme: '主題模式', themeAuto: '自動配合', themeLight: '日間模式', themeDark: '夜間模式', language: '顯示語言', languageAuto: '自動（跟隨系統）', startup: '進入外掛程式時', startupNew: '新增項目', startupRestore: '定位到上次檢視的項目', shortcuts: '快捷鍵', toggleSidebar: '展開／摺疊功能側欄', resetShortcut: '重設快捷鍵', shortcutInvalid: '請使用 Ctrl、Alt 或 Meta 組合鍵，或 F1-F12 功能鍵', shortcutReserved: '此快捷鍵已被編輯器使用', retention: '歷史記錄保留方式', byCount: '按數量', byTime: '按時間', commonDuration: '常用保留時間', customDuration: '自訂：{duration}', exactDays: '確切日數', ageRange: '範圍：{min} 日至 {max}', ageInvalid: '請輸入 {min} 至 {max} 之間的整數日數', maxEntries: '項目數量上限', countRange: '範圍：{min} 至 {max}', countInvalid: '請輸入 {min} 至 {max} 之間的整數', wordWrap: '編輯區自動換行', rememberSidebarState: '記住功能列展開／摺疊狀態'
  },
  editor: { loadingMarkdown: '正在載入 Markdown 編輯器', historyPreview: '歷史項目預覽', readOnlyPreview: '唯讀預覽', noContent: '暫無內容', aria: '閃念文字編輯器', placeholder: '在此輸入文字...' },
  search: { matches: '{count} 個相符結果', noMatches: '找不到相符結果', findReplace: '尋找及取代', findDocument: '在文件中尋找', find: '尋找', previous: '上一個相符結果', next: '下一個相符結果', close: '關閉', closeBar: '關閉尋找列', replaceWith: '取代為', replace: '取代', all: '全部' },
  history: { newEntry: '新增項目', newEntryShortcut: '新增項目（Ctrl+N）', copyText: '複製文字', search: '搜尋歷史記錄', searchScope: '搜尋歷史標題及內容', closeSearch: '關閉歷史搜尋', searching: '正在搜尋...', results: '搜尋結果 {visible}/{total}', title: '歷史記錄', clearAll: '清除全部歷史記錄', clear: '清除歷史記錄', noHistory: '暫無歷史記錄', searchingFull: '正在搜尋標題及內容...', noMatching: '找不到相符的歷史記錄', rename: '重新命名歷史項目', deleteNamed: '刪除歷史項目：{title}', settings: '設定', guide: '使用說明', openFile: '開啟檔案', openFileShortcut: '開啟檔案（Ctrl+O）', saveFile: '儲存檔案', saveFileShortcut: '儲存檔案（Ctrl+S）' },
  status: { characters: '{count} 個字元', unicodeText: 'Unicode 文字', editorStatus: '編輯器狀態', collapseSidebarAria: '摺疊功能側欄（{shortcut}）', expandSidebarAria: '展開功能側欄（{shortcut}）', collapseSidebar: '摺疊功能側欄', expandSidebar: '展開功能側欄', totalCharacters: '字元總數', effectiveCharacters: '有效字元（不含空格）', cjkCharacters: 'CJK 基本漢字', wordsPhrases: '單字／詞組', latinLetters: '拉丁字母', arabicDigits: '阿拉伯數字', punctuation: '標點符號', nonEmptyLines: '行數（不含空白行）', editorMode: '編輯模式', zoom: '縮放：{zoom}%', zoomOut: '縮小', resetZoom: '重設縮放', zoomIn: '放大', lineEndingSaving: '儲存時使用的換行格式', classicMac: '舊式 Mac（CR）', mixedPreserve: '混合（保留）', historyUnicode: '歷史內容以 Unicode 文字儲存', fileEncoding: '檔案編碼：{encoding}', savingEncoding: '儲存時使用：{encoding}', lowConfidence: '自動識別編碼的可信度較低；如文字出現亂碼，請切換編碼後重新讀取。', candidates: '候選編碼：', reloadEncoding: '以此編碼重新讀取' },
  dialogs: { clearTitle: '清除歷史記錄', clearBody: '確定要清除全部 {count} 項歷史記錄嗎？', retentionTitle: '套用歷史記錄保留設定', retentionBody: '新的保留範圍會永久刪除 {count} 項超出限制的歷史記錄。要繼續嗎？', goToLine: '前往指定行', lineNumber: '行號（1-{count}）' },
  help: { startGuide: '開始新手導覽', workflow: '核心流程', history: '歷史項目', historyDesc: '新增或聚焦一項臨時內容', editor: '聚焦編輯', editorDesc: '編輯區只顯示目前項目', autosave: '自動暫存', autosaveDesc: '修改會自動寫回同一歷史項目', features: '常用功能', shortcuts: '快捷鍵速查', close: '關閉使用說明', featureEntryTitle: '以項目暫存', featureEntryDesc: 'Ctrl+N 會立即建立項目；編輯時更新目前項目，刪除後會自動聚焦下一項。', featureSearchTitle: '兩種搜尋範圍', featureSearchDesc: '側欄搜尋會比對所有項目的標題及內容；Ctrl+F、Ctrl+H 只處理目前項目。', featurePreviewTitle: '滑鼠停留預覽及排序', featurePreviewDesc: '在其他項目上停留 500 毫秒，即可在編輯區預覽完整內容；亦可直接拖曳整張卡片排序。', featureMarkdownTitle: '純文字與 Markdown', featureMarkdownDesc: '純文字與 Markdown 共用同一編輯區；Ctrl+/ 可切換目前項目的編輯模式。', featureEncodingTitle: '多種編碼文字檔案', featureEncodingDesc: '開啟檔案時會自動識別常用編碼，亦可手動重新讀取；儲存前可在底部狀態列選擇輸出編碼。', featureEmptyTitle: '自動清理空白項目', featureEmptyDesc: '沒有標題及內容的項目不會保留，亦不會佔用歷史記錄容量。', shortcutNew: '新增項目', shortcutFind: '在項目內尋找', shortcutReplace: '在項目內尋找及取代', shortcutMode: '切換純文字／Markdown', shortcutBold: '粗體', shortcutItalic: '斜體', shortcutOpen: '開啟檔案', shortcutSave: '儲存檔案', shortcutUndo: '復原', shortcutRedo: '重做', shortcutGoLine: '前往指定行', shortcutZoom: '編輯器縮放', shortcutSidebar: '展開／摺疊功能側欄', shortcutRename: '重新命名滑鼠所指項目', shortcutDelete: '刪除滑鼠所指項目', shortcutEscape: '關閉目前功能區或對話框' },
  guide: { skip: '略過', back: '上一步', next: '下一步', finish: '完成', historyTitle: '歷史記錄與聚焦', historyMessage: '編輯區始終只屬於目前聚焦的項目。\n\n• 按一下項目即可聚焦。\n• 在其他項目上停留 500 毫秒可暫時預覽。\n• 直接拖曳整張卡片排序；滑鼠停留時可按 {key:F2} 或 {key:Delete}。', actionsTitle: '常用項目操作', actionsMessage: '頂部只保留處理臨時內容時最常用的操作。\n\n• {bold:新增}會建立並聚焦項目（{key:Ctrl+N}）。\n• {bold:複製}會複製目前顯示的項目。\n• {bold:搜尋}會同時比對所有歷史記錄的標題及內容。', editorTitle: '純文字與 Markdown 編輯', editorMessage: '在此編輯聚焦項目，修改會自動寫回同一歷史記錄。\n\n• {key:Ctrl+/} 切換純文字與 Markdown。\n• {key:Ctrl+F} 尋找，{key:Ctrl+H} 尋找及取代。\n• {key:Ctrl+Z} 與 {key:Ctrl+Shift+Z} 復原及重做操作。', statusTitle: '文件狀態及控制', statusMessage: '將滑鼠移至各資訊區域即可開啟相應控制。\n\n• 查看詳細文件統計。\n• 切換編輯模式及縮放。\n• 選擇換行格式及檔案編碼。\n• 最左側區域用於展開或摺疊功能側欄。', toolsTitle: '檔案、設定及說明', toolsMessage: '全域工具集中在側欄底部。\n\n• 設定主題、語言、歷史記錄保留規則及啟動行為。\n• 從使用說明重新開始此導覽。\n• 開啟不同編碼的文字檔案，或將聚焦項目儲存至每次指定的位置。' },
  notice: { draftSaveFailed: '無法儲存復原草稿', apiUnavailable: 'uTools API 無法使用', nothingUndo: '沒有可復原的操作', undone: '已復原', undoFailed: '復原失敗', nothingRedo: '沒有可重做的操作', redone: '已重做', redoFailed: '重做失敗', saveFailed: '儲存失敗', textTooLong: '文字不可超過 {max} 個字元', fileRequiresUtools: '檔案功能只可在 uTools 外掛程式環境中使用', modeSaveFailed: '無法儲存編輯模式', themeSaveFailed: '無法儲存主題設定', languageSaveFailed: '無法儲存語言設定', startupSaveFailed: '無法儲存啟動行為', shortcutSet: '功能側欄快捷鍵已設為 {shortcut}', shortcutSaveFailed: '無法儲存功能側欄快捷鍵', runInUtools: '請在 uTools 中執行此外掛程式', draftRecovered: '已復原未儲存的草稿', localLoadFailed: '無法載入本機資料', startupApplyFailed: '無法套用啟動行為', conflictCopyTitle: '本機衝突副本', conflictPreserved: '偵測到同步衝突，已保留本機副本。', syncFailed: '歷史記錄同步失敗', copied: '已複製文字', copyFailed: '複製失敗', openedLowConfidence: '已開啟 {name}。編碼識別可信度較低，請檢查文字。', opened: '已開啟 {name}', saved: '已儲存 {name}', nothingSave: '沒有可儲存的內容', noAssociatedFile: '目前內容尚未連結檔案', reloadedEncoding: '已使用 {encoding} 重新讀取', boldMarkdownOnly: '粗體只可在 Markdown 模式使用', italicMarkdownOnly: '斜體只可在 Markdown 模式使用', lineRange: '請輸入 1 至 {count} 之間的行號', zoomSaveFailed: '無法儲存縮放設定', newEntry: '已新增空白項目', newEntryFailed: '無法新增項目', copyWindowKept: '複製失敗，目前視窗會保持開啟。', deletedOne: '已刪除 1 項歷史記錄', deleteFailed: '刪除失敗', titleUpdated: '歷史標題已更新', renameFailed: '重新命名失敗', reorderFailed: '無法儲存歷史排序', historyCleared: '歷史記錄已清除', clearFailed: '清除失敗，已重新載入剩餘歷史記錄。', retentionTimeSet: '歷史記錄保留時間已設為 {duration}', retentionCountSet: '歷史記錄上限已設為 {count} 項', settingsSaveFailed: '無法儲存設定', wordWrapSaveFailed: '無法儲存自動換行設定', tutorialCompleted: '新手導覽已完成', noMatches: '找不到相符結果', enterFind: '請輸入要尋找的文字', replacedOne: '已取代 1 處', replacedMany: '已取代 {count} 處' },
  fileError: { binary: '此檔案可能是二進制檔案，無法以文字方式開啟', encodingLoss: '所選編碼無法表示部分字元，請改用 UTF-8 或其他相容編碼', tooLarge: '檔案太大，最多支援 {max} 個字元', notFile: '所選路徑並非檔案', textTooLong: '文字不可超過 {max} 個字元', generic: '檔案操作失敗' },
  error: { unknown: '未知錯誤', operation: '操作發生錯誤', background: '背景操作發生錯誤', details: '技術詳情', close: '關閉', copyDetails: '複製詳情', renderError: '介面顯示錯誤', reload: '重新載入', renderTitle: '介面暫時無法顯示', renderBody: '請重新載入外掛程式。臨時文字及歷史記錄通常仍儲存在本機。' },
  mode: { text: '純文字', markdown: 'Markdown' }, lineEnding: { mixed: '混合（保留）', classicMac: '舊式 Mac（CR）' }, time: { justNow: '剛剛' }, age: { days: '{count} 日', months: '{count} 個月', years: '{count} 年' }
})
